name: g_faraday
description: A very simple plugin for building hybrid stack apps with flutter
version: 0.5.1-nullsafety.10
homepage: https://github.com/gfaraday/g_faraday

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  g_json: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yuxiaor.flutter.g_faraday
        pluginClass: GFaradayPlugin
      ios:
        pluginClass: GFaradayPlugin
