name: g_faraday
description: A very simple plugin for building hybrid stack apps with flutter
version: 0.4.2
homepage: https://github.com/gfaraday/g_faraday

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  g_json: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yuxiaor.flutter.g_faraday
        pluginClass: GFaradayPlugin
      ios:
        pluginClass: GFaradayPlugin
